// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_home_screen_init();
ui_settingbrightness_screen_init();
ui_settingscreentime_screen_init();
ui_settingwifi_screen_init();
ui_settingwifi2_screen_init();
ui_settingwifi3_screen_init();
ui_settingble1_screen_init();
ui_settingble2_screen_init();
ui_Notification1_screen_init();
ui_Navigation1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_home);
}

void ui_destroy( void )
{ui_home_screen_destroy();
ui_settingbrightness_screen_destroy();
ui_settingscreentime_screen_destroy();
ui_settingwifi_screen_destroy();
ui_settingwifi2_screen_destroy();
ui_settingwifi3_screen_destroy();
ui_settingble1_screen_destroy();
ui_settingble2_screen_destroy();
ui_Notification1_screen_destroy();
ui_Navigation1_screen_destroy();
}

void ui_relocalize( void )
{ui_home_screen_relocalize();
ui_settingbrightness_screen_relocalize();
ui_settingscreentime_screen_relocalize();
ui_settingwifi_screen_relocalize();
ui_settingwifi2_screen_relocalize();
ui_settingwifi3_screen_relocalize();
ui_settingble1_screen_relocalize();
ui_settingble2_screen_relocalize();
ui_Notification1_screen_relocalize();
ui_Navigation1_screen_relocalize();
}
