// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef _PROJECT_UI_H
#define _PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_home.h"
#include "ui_settingbrightness.h"
#include "ui_settingscreentime.h"
#include "ui_settingwifi.h"
#include "ui_settingwifi2.h"
#include "ui_settingwifi3.h"
#include "ui_settingble1.h"
#include "ui_settingble2.h"
#include "ui_Notification1.h"
#include "ui_Navigation1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_bar_home_png);   // assets/bar_home.png
LV_IMG_DECLARE( ui_img_battery_png);   // assets/battery.png
LV_IMG_DECLARE( ui_img_battery_80_png);   // assets/battery_80.png
LV_IMG_DECLARE( ui_img_battery_50_png);   // assets/battery_50.png
LV_IMG_DECLARE( ui_img_battery_30_png);   // assets/battery_30.png
LV_IMG_DECLARE( ui_img_battery_10_png);   // assets/battery_10.png
LV_IMG_DECLARE( ui_img_battery_5_png);   // assets/battery_5.png
LV_IMG_DECLARE( ui_img_ble_connect_png);   // assets/ble_connect.png
LV_IMG_DECLARE( ui_img_ble_disconnect_png);   // assets/ble_disconnect.png
LV_IMG_DECLARE( ui_img_wifi_connect_png);   // assets/wifi_connect.png
LV_IMG_DECLARE( ui_img_wifi_disconnect_png);   // assets/wifi_disconnect.png
LV_IMG_DECLARE( ui_img_motor_png);   // assets/motor.png
LV_IMG_DECLARE( ui_img_brightness_png);   // assets/brightness.png
LV_IMG_DECLARE( ui_img_bar_brightness_png);   // assets/bar_brightness.png
LV_IMG_DECLARE( ui_img_adjust_brightness_png);   // assets/adjust_brightness.png
LV_IMG_DECLARE( ui_img_setting_mask_png);   // assets/setting_mask.png
LV_IMG_DECLARE( ui_img_bar_screentime_png);   // assets/bar_screentime.png
LV_IMG_DECLARE( ui_img_ngoacnhontrai_png);   // assets/ngoacnhontrai.png
LV_IMG_DECLARE( ui_img_ngoacnhonphai_png);   // assets/ngoacnhonphai.png
LV_IMG_DECLARE( ui_img_screentime_png);   // assets/screentime.png
LV_IMG_DECLARE( ui_img_bar_wifisetting_png);   // assets/bar_wifisetting.png
LV_IMG_DECLARE( ui_img_wifi_disconnect_2_png);   // assets/wifi_disconnect_2.png
LV_IMG_DECLARE( ui_img_wifi_connect_1_png);   // assets/wifi_connect_1.png
LV_IMG_DECLARE( ui_img_loading_png);   // assets/loading.png
LV_IMG_DECLARE( ui_img_iconwifi_small_png);   // assets/iconwifi_small.png
LV_IMG_DECLARE( ui_img_iconwifi_connect_small_png);   // assets/iconwifi_connect_small.png
LV_IMG_DECLARE( ui_img_ngocnhonlen_png);   // assets/ngocnhonlen.png
LV_IMG_DECLARE( ui_img_connect_success_small_png);   // assets/connect_success_small.png
LV_IMG_DECLARE( ui_img_keyboard_png);   // assets/keyboard.png
LV_IMG_DECLARE( ui_img_bar_ble_png);   // assets/bar_ble.png
LV_IMG_DECLARE( ui_img_ble_disconnect_1_png);   // assets/ble_disconnect_1.png
LV_IMG_DECLARE( ui_img_ble_connect_1_png);   // assets/ble_connect_1.png
LV_IMG_DECLARE( ui_img_ble_disconnect_icon_png);   // assets/ble_disconnect_icon.png
LV_IMG_DECLARE( ui_img_ble_connect_icon_png);   // assets/ble_connect_icon.png
LV_IMG_DECLARE( ui_img_bar_notification_png);   // assets/bar_notification.png
LV_IMG_DECLARE( ui_img_facebook_png);   // assets/facebook.png
LV_IMG_DECLARE( ui_img_maps_png);   // assets/maps.png
LV_IMG_DECLARE( ui_img_message_png);   // assets/message.png
LV_IMG_DECLARE( ui_img_messenger_png);   // assets/messenger.png
LV_IMG_DECLARE( ui_img_tiktok_png);   // assets/tiktok.png
LV_IMG_DECLARE( ui_img_youtube_png);   // assets/youtube.png
LV_IMG_DECLARE( ui_img_zalo_png);   // assets/zalo.png
LV_IMG_DECLARE( ui_img_other_png);   // assets/other.png
LV_IMG_DECLARE( ui_img_telegram_png);   // assets/telegram.png
LV_IMG_DECLARE( ui_img_call_png);   // assets/call.png
LV_IMG_DECLARE( ui_img_instagram_png);   // assets/instagram.png
LV_IMG_DECLARE( ui_img_dithang_png);   // assets/dithang.png
LV_IMG_DECLARE( ui_img_retrai_png);   // assets/retrai.png
LV_IMG_DECLARE( ui_img_rephai_png);   // assets/rephai.png
LV_IMG_DECLARE( ui_img_vongxoay1_png);   // assets/vongxoay1.png
LV_IMG_DECLARE( ui_img_vongxoay_png);   // assets/vongxoay.png
LV_IMG_DECLARE( ui_img_vongxoay2_png);   // assets/vongxoay2.png
LV_IMG_DECLARE( ui_img_vongxoay3_png);   // assets/vongxoay3.png
LV_IMG_DECLARE( ui_img_vongxoay4_png);   // assets/vongxoay4.png
LV_IMG_DECLARE( ui_img_vongxoay5_png);   // assets/vongxoay5.png
LV_IMG_DECLARE( ui_img_dibenphai_png);   // assets/dibenphai.png
LV_IMG_DECLARE( ui_img_dichden_png);   // assets/dichden.png
LV_IMG_DECLARE( ui_img_quaydau_png);   // assets/quaydau.png
LV_IMG_DECLARE( ui_img_dibentrai_png);   // assets/dibentrai.png
LV_IMG_DECLARE( ui_img_bar_notification_small_png);   // assets/bar_notification_small.png
LV_IMG_DECLARE( ui_img_call_small_png);   // assets/call_small.png
LV_IMG_DECLARE( ui_img_facebook_small_png);   // assets/facebook_small.png
LV_IMG_DECLARE( ui_img_other_small_png);   // assets/other_small.png
LV_IMG_DECLARE( ui_img_instagram_small_png);   // assets/instagram_small.png
LV_IMG_DECLARE( ui_img_maps_small_png);   // assets/maps_small.png
LV_IMG_DECLARE( ui_img_message_small_png);   // assets/message_small.png
LV_IMG_DECLARE( ui_img_messenger_small_png);   // assets/messenger_small.png
LV_IMG_DECLARE( ui_img_telegram_small_png);   // assets/telegram_small.png
LV_IMG_DECLARE( ui_img_tiktok_small_png);   // assets/tiktok_small.png
LV_IMG_DECLARE( ui_img_youtube_smal_png);   // assets/youtube_smal.png
LV_IMG_DECLARE( ui_img_zalo_small_png);   // assets/zalo_small.png

// FONTS
LV_FONT_DECLARE( ui_font_SVNAvo10);
LV_FONT_DECLARE( ui_font_SVNAvo16);
LV_FONT_DECLARE( ui_font_SVNAvo20);
LV_FONT_DECLARE( ui_font_SVNRounded17);
LV_FONT_DECLARE( ui_font_SVNRounded23);
LV_FONT_DECLARE( ui_font_SVNRounded30);
LV_FONT_DECLARE( ui_font_SVNRounded68);
LV_FONT_DECLARE( ui_font_SVNRrounded40);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
