// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern void ui_home_screen_relocalize(void);
extern lv_obj_t *ui_home;
extern lv_obj_t *ui_homebutton;
extern lv_obj_t *ui_title;
extern lv_obj_t *ui_battery;
extern lv_obj_t *ui_battery80;
extern lv_obj_t *ui_battery50;
extern lv_obj_t *ui_battery30;
extern lv_obj_t *ui_battery10;
extern lv_obj_t *ui_battery5;
extern lv_obj_t *ui_clock;
extern lv_obj_t *ui_bleconnect;
extern lv_obj_t *ui_bledisconnect;
extern lv_obj_t *ui_wificonnect;
extern lv_obj_t *ui_wifidisconnect;
extern lv_obj_t *ui_motor;
// CUSTOM VARIABLES
extern lv_obj_t *uic_home;
extern lv_obj_t *uic_homebutton;
extern lv_obj_t *uic_title;
extern lv_obj_t *uic_battery;
extern lv_obj_t *uic_CLock;
extern lv_obj_t *uic_bleconnect;
extern lv_obj_t *uic_wificonnect;
extern lv_obj_t *uic_wifidisconnect;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

