// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_NAVIGATION1_H
#define UI_NAVIGATION1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Navigation1
extern void ui_Navigation1_screen_init(void);
extern void ui_Navigation1_screen_destroy(void);
extern void ui_Navigation1_screen_relocalize(void);
extern lv_obj_t *ui_Navigation1;
extern lv_obj_t *ui_clock1;
extern lv_obj_t *ui_arrow;
extern lv_obj_t *ui_retrai;
extern lv_obj_t *ui_rephai;
extern lv_obj_t *ui_vongxoay1;
extern lv_obj_t *ui_vongxoay;
extern lv_obj_t *ui_vongxoay2;
extern lv_obj_t *ui_vongxoay3;
extern lv_obj_t *ui_vongxoay4;
extern lv_obj_t *ui_vongxoay5;
extern lv_obj_t *ui_dibenphai;
extern lv_obj_t *ui_dichden;
extern lv_obj_t *ui_quaydau;
extern lv_obj_t *ui_dibentrai;
extern lv_obj_t *ui_battery1;
extern lv_obj_t *ui_battery3;
extern lv_obj_t *ui_battery4;
extern lv_obj_t *ui_battery6;
extern lv_obj_t *ui_battery7;
extern lv_obj_t *ui_battery8;
extern lv_obj_t *ui_quangduong;
extern lv_obj_t *ui_huongdan;
extern lv_obj_t *ui_notificationsmall;
extern lv_obj_t *ui_iconnotificationsmall;
extern lv_obj_t *ui_Image29;
extern lv_obj_t *ui_Image34;
extern lv_obj_t *ui_Image30;
extern lv_obj_t *ui_Image31;
extern lv_obj_t *ui_Image32;
extern lv_obj_t *ui_Image33;
extern lv_obj_t *ui_Image35;
extern lv_obj_t *ui_Image36;
extern lv_obj_t *ui_Image37;
extern lv_obj_t *ui_Image38;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Navigation1;
extern lv_obj_t *uic_arrow;
extern lv_obj_t *uic_quangduong;
extern lv_obj_t *uic_huongdan;
extern lv_obj_t *uic_notificationsmall;
extern lv_obj_t *uic_iconnotificationsmall;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

