// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"

lv_obj_t *uic_battery2;
lv_obj_t *uic_iconnotification;
lv_obj_t *uic_notify_name;
lv_obj_t *uic_newnotify;
lv_obj_t *uic_clock2;
lv_obj_t *uic_Notification1;
lv_obj_t *ui_Notification1 = NULL;lv_obj_t *ui_clock2 = NULL;lv_obj_t *ui_newnotify = NULL;lv_obj_t *ui_notifyname = NULL;lv_obj_t *ui_notifycontent = NULL;lv_obj_t *ui_iconnotification = NULL;lv_obj_t *ui_maps = NULL;lv_obj_t *ui_message = NULL;lv_obj_t *ui_messenger = NULL;lv_obj_t *ui_tiktok = NULL;lv_obj_t *ui_youtube = NULL;lv_obj_t *ui_zalo = NULL;lv_obj_t *ui_other = NULL;lv_obj_t *ui_telegram = NULL;lv_obj_t *ui_call = NULL;lv_obj_t *ui_instagram = NULL;lv_obj_t *ui_battery2 = NULL;lv_obj_t *ui_battery80_2 = NULL;lv_obj_t *ui_battery50_2 = NULL;lv_obj_t *ui_battery30_2 = NULL;lv_obj_t *ui_battery10_2 = NULL;lv_obj_t *ui_battery5_2 = NULL;
// event funtions

// build funtions

void ui_Notification1_screen_init(void)
{
ui_Notification1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Notification1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Notification1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Notification1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clock2 = lv_label_create(ui_Notification1);
lv_obj_set_width( ui_clock2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock2, 0 );
lv_obj_set_y( ui_clock2, -80 );
lv_obj_set_align( ui_clock2, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock2,"12:12");
lv_obj_set_style_text_color(ui_clock2, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_clock2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_clock2, &ui_font_SVNRounded30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_newnotify = lv_img_create(ui_Notification1);
lv_img_set_src(ui_newnotify, &ui_img_bar_notification_png);
lv_obj_set_width( ui_newnotify, LV_SIZE_CONTENT);  /// 193
lv_obj_set_height( ui_newnotify, LV_SIZE_CONTENT);   /// 55
lv_obj_set_align( ui_newnotify, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_newnotify, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_newnotify, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_notifyname = lv_label_create(ui_newnotify);
lv_obj_set_width( ui_notifyname, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_notifyname, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_notifyname, 17 );
lv_obj_set_y( ui_notifyname, -16 );
lv_obj_set_align( ui_notifyname, LV_ALIGN_CENTER );
lv_label_set_text(ui_notifyname,"NGUYEN DUC KHA");
lv_obj_set_style_text_color(ui_notifyname, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_notifyname, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_notifyname, &ui_font_SVNRounded17, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_notifycontent = lv_label_create(ui_newnotify);
lv_obj_set_width( ui_notifycontent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_notifycontent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_notifycontent, 17 );
lv_obj_set_y( ui_notifycontent, 9 );
lv_obj_set_align( ui_notifycontent, LV_ALIGN_CENTER );
lv_label_set_text(ui_notifycontent,"Xin chao ban dang co\nmot tin nhan moi");
lv_obj_set_style_text_color(ui_notifycontent, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_notifycontent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_notifycontent, &ui_font_SVNAvo10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_iconnotification = lv_img_create(ui_Notification1);
lv_img_set_src(ui_iconnotification, &ui_img_facebook_png);
lv_obj_set_width( ui_iconnotification, LV_SIZE_CONTENT);  /// 41
lv_obj_set_height( ui_iconnotification, LV_SIZE_CONTENT);   /// 41
lv_obj_set_x( ui_iconnotification, -68 );
lv_obj_set_y( ui_iconnotification, 0 );
lv_obj_set_align( ui_iconnotification, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_iconnotification, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_iconnotification, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_maps = lv_img_create(ui_iconnotification);
lv_img_set_src(ui_maps, &ui_img_maps_png);
lv_obj_set_width( ui_maps, LV_SIZE_CONTENT);  /// 41
lv_obj_set_height( ui_maps, LV_SIZE_CONTENT);   /// 41
lv_obj_set_align( ui_maps, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_maps, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_maps, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_message = lv_img_create(ui_iconnotification);
lv_img_set_src(ui_message, &ui_img_message_png);
lv_obj_set_width( ui_message, LV_SIZE_CONTENT);  /// 41
lv_obj_set_height( ui_message, LV_SIZE_CONTENT);   /// 41
lv_obj_set_align( ui_message, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_message, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_message, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_messenger = lv_img_create(ui_iconnotification);
lv_img_set_src(ui_messenger, &ui_img_messenger_png);
lv_obj_set_width( ui_messenger, LV_SIZE_CONTENT);  /// 43
lv_obj_set_height( ui_messenger, LV_SIZE_CONTENT);   /// 42
lv_obj_set_align( ui_messenger, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_messenger, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_messenger, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_tiktok = lv_img_create(ui_iconnotification);
lv_img_set_src(ui_tiktok, &ui_img_tiktok_png);
lv_obj_set_width( ui_tiktok, LV_SIZE_CONTENT);  /// 41
lv_obj_set_height( ui_tiktok, LV_SIZE_CONTENT);   /// 41
lv_obj_set_align( ui_tiktok, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_tiktok, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_tiktok, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_youtube = lv_img_create(ui_iconnotification);
lv_img_set_src(ui_youtube, &ui_img_youtube_png);
lv_obj_set_width( ui_youtube, LV_SIZE_CONTENT);  /// 41
lv_obj_set_height( ui_youtube, LV_SIZE_CONTENT);   /// 41
lv_obj_set_align( ui_youtube, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_youtube, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_youtube, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_zalo = lv_img_create(ui_iconnotification);
lv_img_set_src(ui_zalo, &ui_img_zalo_png);
lv_obj_set_width( ui_zalo, LV_SIZE_CONTENT);  /// 42
lv_obj_set_height( ui_zalo, LV_SIZE_CONTENT);   /// 41
lv_obj_set_align( ui_zalo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_zalo, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_zalo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_other = lv_img_create(ui_iconnotification);
lv_img_set_src(ui_other, &ui_img_other_png);
lv_obj_set_width( ui_other, LV_SIZE_CONTENT);  /// 41
lv_obj_set_height( ui_other, LV_SIZE_CONTENT);   /// 41
lv_obj_set_align( ui_other, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_other, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_other, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_telegram = lv_img_create(ui_iconnotification);
lv_img_set_src(ui_telegram, &ui_img_telegram_png);
lv_obj_set_width( ui_telegram, LV_SIZE_CONTENT);  /// 41
lv_obj_set_height( ui_telegram, LV_SIZE_CONTENT);   /// 41
lv_obj_set_align( ui_telegram, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_telegram, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_telegram, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_call = lv_img_create(ui_iconnotification);
lv_img_set_src(ui_call, &ui_img_call_png);
lv_obj_set_width( ui_call, LV_SIZE_CONTENT);  /// 41
lv_obj_set_height( ui_call, LV_SIZE_CONTENT);   /// 41
lv_obj_set_align( ui_call, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_call, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_call, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_instagram = lv_img_create(ui_iconnotification);
lv_img_set_src(ui_instagram, &ui_img_instagram_png);
lv_obj_set_width( ui_instagram, LV_SIZE_CONTENT);  /// 41
lv_obj_set_height( ui_instagram, LV_SIZE_CONTENT);   /// 41
lv_obj_set_align( ui_instagram, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_instagram, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_instagram, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery2 = lv_img_create(ui_Notification1);
lv_img_set_src(ui_battery2, &ui_img_battery_png);
lv_obj_set_width( ui_battery2, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery2, LV_SIZE_CONTENT);   /// 15
lv_obj_set_x( ui_battery2, 0 );
lv_obj_set_y( ui_battery2, -55 );
lv_obj_set_align( ui_battery2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery80_2 = lv_img_create(ui_battery2);
lv_img_set_src(ui_battery80_2, &ui_img_battery_80_png);
lv_obj_set_width( ui_battery80_2, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery80_2, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_battery80_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery80_2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery80_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery50_2 = lv_img_create(ui_battery2);
lv_img_set_src(ui_battery50_2, &ui_img_battery_50_png);
lv_obj_set_width( ui_battery50_2, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery50_2, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_battery50_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery50_2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery50_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery30_2 = lv_img_create(ui_battery2);
lv_img_set_src(ui_battery30_2, &ui_img_battery_30_png);
lv_obj_set_width( ui_battery30_2, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery30_2, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_battery30_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery30_2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery30_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery10_2 = lv_img_create(ui_battery2);
lv_img_set_src(ui_battery10_2, &ui_img_battery_10_png);
lv_obj_set_width( ui_battery10_2, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery10_2, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_battery10_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery10_2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery10_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery5_2 = lv_img_create(ui_battery2);
lv_img_set_src(ui_battery5_2, &ui_img_battery_5_png);
lv_obj_set_width( ui_battery5_2, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery5_2, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_battery5_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery5_2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery5_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_Notification1 = ui_Notification1;
uic_clock2 = ui_clock2;
uic_newnotify = ui_newnotify;
uic_notify_name = ui_notifyname;
uic_iconnotification = ui_iconnotification;
uic_battery2 = ui_battery2;

}

void ui_Notification1_screen_destroy(void)
{
   if (ui_Notification1) lv_obj_del(ui_Notification1);

// NULL screen variables
uic_Notification1= NULL;
ui_Notification1= NULL;
uic_clock2= NULL;
ui_clock2= NULL;
uic_newnotify= NULL;
ui_newnotify= NULL;
uic_notify_name= NULL;
ui_notifyname= NULL;
ui_notifycontent= NULL;
uic_iconnotification= NULL;
ui_iconnotification= NULL;
ui_maps= NULL;
ui_message= NULL;
ui_messenger= NULL;
ui_tiktok= NULL;
ui_youtube= NULL;
ui_zalo= NULL;
ui_other= NULL;
ui_telegram= NULL;
ui_call= NULL;
ui_instagram= NULL;
uic_battery2= NULL;
ui_battery2= NULL;
ui_battery80_2= NULL;
ui_battery50_2= NULL;
ui_battery30_2= NULL;
ui_battery10_2= NULL;
ui_battery5_2= NULL;

}

void ui_Notification1_screen_relocalize(void)
{
// label widgets on screen

}
