// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_NOTIFICATION1_H
#define UI_NOTIFICATION1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Notification1
extern void ui_Notification1_screen_init(void);
extern void ui_Notification1_screen_destroy(void);
extern void ui_Notification1_screen_relocalize(void);
extern lv_obj_t *ui_Notification1;
extern lv_obj_t *ui_clock2;
extern lv_obj_t *ui_newnotify;
extern lv_obj_t *ui_notifyname;
extern lv_obj_t *ui_notifycontent;
extern lv_obj_t *ui_iconnotification;
extern lv_obj_t *ui_maps;
extern lv_obj_t *ui_message;
extern lv_obj_t *ui_messenger;
extern lv_obj_t *ui_tiktok;
extern lv_obj_t *ui_youtube;
extern lv_obj_t *ui_zalo;
extern lv_obj_t *ui_other;
extern lv_obj_t *ui_telegram;
extern lv_obj_t *ui_call;
extern lv_obj_t *ui_instagram;
extern lv_obj_t *ui_battery2;
extern lv_obj_t *ui_battery80_2;
extern lv_obj_t *ui_battery50_2;
extern lv_obj_t *ui_battery30_2;
extern lv_obj_t *ui_battery10_2;
extern lv_obj_t *ui_battery5_2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Notification1;
extern lv_obj_t *uic_clock2;
extern lv_obj_t *uic_newnotify;
extern lv_obj_t *uic_notify_name;
extern lv_obj_t *uic_iconnotification;
extern lv_obj_t *uic_battery2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

