// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"

lv_obj_t *uic_iconnotificationsmall;
lv_obj_t *uic_notificationsmall;
lv_obj_t *uic_huongdan;
lv_obj_t *uic_quangduong;
lv_obj_t *uic_arrow;
lv_obj_t *uic_Navigation1;
lv_obj_t *ui_Navigation1 = NULL;lv_obj_t *ui_clock1 = NULL;lv_obj_t *ui_arrow = NULL;lv_obj_t *ui_retrai = NULL;lv_obj_t *ui_rephai = NULL;lv_obj_t *ui_vongxoay1 = NULL;lv_obj_t *ui_vongxoay = NULL;lv_obj_t *ui_vongxoay2 = NULL;lv_obj_t *ui_vongxoay3 = NULL;lv_obj_t *ui_vongxoay4 = NULL;lv_obj_t *ui_vongxoay5 = NULL;lv_obj_t *ui_dibenphai = NULL;lv_obj_t *ui_dichden = NULL;lv_obj_t *ui_quaydau = NULL;lv_obj_t *ui_dibentrai = NULL;lv_obj_t *ui_battery1 = NULL;lv_obj_t *ui_battery3 = NULL;lv_obj_t *ui_battery4 = NULL;lv_obj_t *ui_battery6 = NULL;lv_obj_t *ui_battery7 = NULL;lv_obj_t *ui_battery8 = NULL;lv_obj_t *ui_quangduong = NULL;lv_obj_t *ui_huongdan = NULL;lv_obj_t *ui_notificationsmall = NULL;lv_obj_t *ui_iconnotificationsmall = NULL;lv_obj_t *ui_Image29 = NULL;lv_obj_t *ui_Image34 = NULL;lv_obj_t *ui_Image30 = NULL;lv_obj_t *ui_Image31 = NULL;lv_obj_t *ui_Image32 = NULL;lv_obj_t *ui_Image33 = NULL;lv_obj_t *ui_Image35 = NULL;lv_obj_t *ui_Image36 = NULL;lv_obj_t *ui_Image37 = NULL;lv_obj_t *ui_Image38 = NULL;
// event funtions

// build funtions

void ui_Navigation1_screen_init(void)
{
ui_Navigation1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Navigation1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Navigation1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Navigation1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clock1 = lv_label_create(ui_Navigation1);
lv_obj_set_width( ui_clock1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock1, 0 );
lv_obj_set_y( ui_clock1, -80 );
lv_obj_set_align( ui_clock1, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock1,"12:12");
lv_obj_set_style_text_color(ui_clock1, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_clock1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_clock1, &ui_font_SVNRounded30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arrow = lv_img_create(ui_Navigation1);
lv_img_set_src(ui_arrow, &ui_img_dithang_png);
lv_obj_set_width( ui_arrow, LV_SIZE_CONTENT);  /// 55
lv_obj_set_height( ui_arrow, LV_SIZE_CONTENT);   /// 75
lv_obj_set_x( ui_arrow, -20 );
lv_obj_set_y( ui_arrow, 0 );
lv_obj_set_align( ui_arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_retrai = lv_img_create(ui_arrow);
lv_img_set_src(ui_retrai, &ui_img_retrai_png);
lv_obj_set_width( ui_retrai, LV_SIZE_CONTENT);  /// 51
lv_obj_set_height( ui_retrai, LV_SIZE_CONTENT);   /// 74
lv_obj_set_align( ui_retrai, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_retrai, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_retrai, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rephai = lv_img_create(ui_arrow);
lv_img_set_src(ui_rephai, &ui_img_rephai_png);
lv_obj_set_width( ui_rephai, LV_SIZE_CONTENT);  /// 52
lv_obj_set_height( ui_rephai, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_rephai, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rephai, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_rephai, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_vongxoay1 = lv_img_create(ui_arrow);
lv_img_set_src(ui_vongxoay1, &ui_img_vongxoay1_png);
lv_obj_set_width( ui_vongxoay1, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_vongxoay1, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_vongxoay1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_vongxoay1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_vongxoay1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_vongxoay = lv_img_create(ui_arrow);
lv_img_set_src(ui_vongxoay, &ui_img_vongxoay_png);
lv_obj_set_width( ui_vongxoay, LV_SIZE_CONTENT);  /// 63
lv_obj_set_height( ui_vongxoay, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_vongxoay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_vongxoay, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_vongxoay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_vongxoay2 = lv_img_create(ui_arrow);
lv_img_set_src(ui_vongxoay2, &ui_img_vongxoay2_png);
lv_obj_set_width( ui_vongxoay2, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_vongxoay2, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_vongxoay2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_vongxoay2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_vongxoay2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_vongxoay3 = lv_img_create(ui_arrow);
lv_img_set_src(ui_vongxoay3, &ui_img_vongxoay3_png);
lv_obj_set_width( ui_vongxoay3, LV_SIZE_CONTENT);  /// 63
lv_obj_set_height( ui_vongxoay3, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_vongxoay3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_vongxoay3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_vongxoay3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_vongxoay4 = lv_img_create(ui_arrow);
lv_img_set_src(ui_vongxoay4, &ui_img_vongxoay4_png);
lv_obj_set_width( ui_vongxoay4, LV_SIZE_CONTENT);  /// 63
lv_obj_set_height( ui_vongxoay4, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_vongxoay4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_vongxoay4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_vongxoay4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_vongxoay5 = lv_img_create(ui_arrow);
lv_img_set_src(ui_vongxoay5, &ui_img_vongxoay5_png);
lv_obj_set_width( ui_vongxoay5, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_vongxoay5, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_vongxoay5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_vongxoay5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_vongxoay5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_dibenphai = lv_img_create(ui_arrow);
lv_img_set_src(ui_dibenphai, &ui_img_dibenphai_png);
lv_obj_set_width( ui_dibenphai, LV_SIZE_CONTENT);  /// 57
lv_obj_set_height( ui_dibenphai, LV_SIZE_CONTENT);   /// 57
lv_obj_set_align( ui_dibenphai, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dibenphai, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_dibenphai, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_dichden = lv_img_create(ui_arrow);
lv_img_set_src(ui_dichden, &ui_img_dichden_png);
lv_obj_set_width( ui_dichden, LV_SIZE_CONTENT);  /// 54
lv_obj_set_height( ui_dichden, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_dichden, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dichden, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_dichden, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_quaydau = lv_img_create(ui_arrow);
lv_img_set_src(ui_quaydau, &ui_img_quaydau_png);
lv_obj_set_width( ui_quaydau, LV_SIZE_CONTENT);  /// 74
lv_obj_set_height( ui_quaydau, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_quaydau, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_quaydau, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_quaydau, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_dibentrai = lv_img_create(ui_arrow);
lv_img_set_src(ui_dibentrai, &ui_img_dibentrai_png);
lv_obj_set_width( ui_dibentrai, LV_SIZE_CONTENT);  /// 57
lv_obj_set_height( ui_dibentrai, LV_SIZE_CONTENT);   /// 57
lv_obj_set_align( ui_dibentrai, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dibentrai, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_dibentrai, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery1 = lv_img_create(ui_Navigation1);
lv_img_set_src(ui_battery1, &ui_img_battery_png);
lv_obj_set_width( ui_battery1, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery1, LV_SIZE_CONTENT);   /// 15
lv_obj_set_x( ui_battery1, 0 );
lv_obj_set_y( ui_battery1, -55 );
lv_obj_set_align( ui_battery1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery3 = lv_img_create(ui_battery1);
lv_img_set_src(ui_battery3, &ui_img_battery_80_png);
lv_obj_set_width( ui_battery3, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery3, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_battery3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery4 = lv_img_create(ui_battery1);
lv_img_set_src(ui_battery4, &ui_img_battery_50_png);
lv_obj_set_width( ui_battery4, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery4, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_battery4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery6 = lv_img_create(ui_battery1);
lv_img_set_src(ui_battery6, &ui_img_battery_30_png);
lv_obj_set_width( ui_battery6, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery6, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_battery6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery7 = lv_img_create(ui_battery1);
lv_img_set_src(ui_battery7, &ui_img_battery_10_png);
lv_obj_set_width( ui_battery7, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery7, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_battery7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battery8 = lv_img_create(ui_battery1);
lv_img_set_src(ui_battery8, &ui_img_battery_5_png);
lv_obj_set_width( ui_battery8, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_battery8, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_battery8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battery8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battery8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_quangduong = lv_label_create(ui_Navigation1);
lv_obj_set_width( ui_quangduong, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_quangduong, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_quangduong, 50 );
lv_obj_set_y( ui_quangduong, -15 );
lv_obj_set_align( ui_quangduong, LV_ALIGN_CENTER );
lv_label_set_text(ui_quangduong,"500m");
lv_obj_set_style_text_color(ui_quangduong, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_quangduong, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_quangduong, &ui_font_SVNRounded30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_huongdan = lv_label_create(ui_Navigation1);
lv_obj_set_width( ui_huongdan, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_huongdan, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_huongdan, 0 );
lv_obj_set_y( ui_huongdan, 55 );
lv_obj_set_align( ui_huongdan, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_huongdan,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_huongdan,"Re trai");
lv_obj_set_style_text_color(ui_huongdan, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_huongdan, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_huongdan, &ui_font_SVNAvo20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_notificationsmall = lv_img_create(ui_huongdan);
lv_img_set_src(ui_notificationsmall, &ui_img_bar_notification_small_png);
lv_obj_set_width( ui_notificationsmall, LV_SIZE_CONTENT);  /// 135
lv_obj_set_height( ui_notificationsmall, LV_SIZE_CONTENT);   /// 28
lv_obj_set_align( ui_notificationsmall, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_notificationsmall, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_notificationsmall, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_iconnotificationsmall = lv_img_create(ui_notificationsmall);
lv_img_set_src(ui_iconnotificationsmall, &ui_img_call_small_png);
lv_obj_set_width( ui_iconnotificationsmall, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_iconnotificationsmall, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_iconnotificationsmall, -53 );
lv_obj_set_y( ui_iconnotificationsmall, 0 );
lv_obj_set_align( ui_iconnotificationsmall, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_iconnotificationsmall, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_iconnotificationsmall, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image29 = lv_img_create(ui_iconnotificationsmall);
lv_img_set_src(ui_Image29, &ui_img_facebook_small_png);
lv_obj_set_width( ui_Image29, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image29, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image29, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image29, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image29, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image34 = lv_img_create(ui_iconnotificationsmall);
lv_img_set_src(ui_Image34, &ui_img_other_small_png);
lv_obj_set_width( ui_Image34, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image34, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image34, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image34, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image34, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image30 = lv_img_create(ui_iconnotificationsmall);
lv_img_set_src(ui_Image30, &ui_img_instagram_small_png);
lv_obj_set_width( ui_Image30, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_Image30, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image30, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image30, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image30, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image31 = lv_img_create(ui_iconnotificationsmall);
lv_img_set_src(ui_Image31, &ui_img_maps_small_png);
lv_obj_set_width( ui_Image31, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image31, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image31, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image31, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image31, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image32 = lv_img_create(ui_iconnotificationsmall);
lv_img_set_src(ui_Image32, &ui_img_message_small_png);
lv_obj_set_width( ui_Image32, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image32, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image32, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image32, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image32, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image33 = lv_img_create(ui_iconnotificationsmall);
lv_img_set_src(ui_Image33, &ui_img_messenger_small_png);
lv_obj_set_width( ui_Image33, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image33, LV_SIZE_CONTENT);   /// 21
lv_obj_set_align( ui_Image33, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image33, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image33, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image35 = lv_img_create(ui_iconnotificationsmall);
lv_img_set_src(ui_Image35, &ui_img_telegram_small_png);
lv_obj_set_width( ui_Image35, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_Image35, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image35, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image35, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image35, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image36 = lv_img_create(ui_iconnotificationsmall);
lv_img_set_src(ui_Image36, &ui_img_tiktok_small_png);
lv_obj_set_width( ui_Image36, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image36, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image36, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image36, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image36, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image37 = lv_img_create(ui_iconnotificationsmall);
lv_img_set_src(ui_Image37, &ui_img_youtube_smal_png);
lv_obj_set_width( ui_Image37, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_Image37, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image37, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image37, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image37, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image38 = lv_img_create(ui_iconnotificationsmall);
lv_img_set_src(ui_Image38, &ui_img_zalo_small_png);
lv_obj_set_width( ui_Image38, LV_SIZE_CONTENT);  /// 21
lv_obj_set_height( ui_Image38, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image38, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image38, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image38, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_Navigation1 = ui_Navigation1;
uic_arrow = ui_arrow;
uic_quangduong = ui_quangduong;
uic_huongdan = ui_huongdan;
uic_notificationsmall = ui_notificationsmall;
uic_iconnotificationsmall = ui_iconnotificationsmall;

}

void ui_Navigation1_screen_destroy(void)
{
   if (ui_Navigation1) lv_obj_del(ui_Navigation1);

// NULL screen variables
uic_Navigation1= NULL;
ui_Navigation1= NULL;
ui_clock1= NULL;
uic_arrow= NULL;
ui_arrow= NULL;
ui_retrai= NULL;
ui_rephai= NULL;
ui_vongxoay1= NULL;
ui_vongxoay= NULL;
ui_vongxoay2= NULL;
ui_vongxoay3= NULL;
ui_vongxoay4= NULL;
ui_vongxoay5= NULL;
ui_dibenphai= NULL;
ui_dichden= NULL;
ui_quaydau= NULL;
ui_dibentrai= NULL;
ui_battery1= NULL;
ui_battery3= NULL;
ui_battery4= NULL;
ui_battery6= NULL;
ui_battery7= NULL;
ui_battery8= NULL;
uic_quangduong= NULL;
ui_quangduong= NULL;
uic_huongdan= NULL;
ui_huongdan= NULL;
uic_notificationsmall= NULL;
ui_notificationsmall= NULL;
uic_iconnotificationsmall= NULL;
ui_iconnotificationsmall= NULL;
ui_Image29= NULL;
ui_Image34= NULL;
ui_Image30= NULL;
ui_Image31= NULL;
ui_Image32= NULL;
ui_Image33= NULL;
ui_Image35= NULL;
ui_Image36= NULL;
ui_Image37= NULL;
ui_Image38= NULL;

}

void ui_Navigation1_screen_relocalize(void)
{
// label widgets on screen

}
