// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"

lv_obj_t *uic_keyboard;
lv_obj_t *uic_enterbutton;
lv_obj_t *uic_password;
lv_obj_t *uic_passwordbutton;
lv_obj_t *uic_ngoacnhonlen1;
lv_obj_t *uic_settingwifi3;
lv_obj_t *ui_settingwifi3 = NULL;lv_obj_t *ui_iconwifi1 = NULL;lv_obj_t *ui_ngoacnhonlen1 = NULL;lv_obj_t *ui_passwordbutton = NULL;lv_obj_t *ui_password = NULL;lv_obj_t *ui_enterbutton = NULL;lv_obj_t *ui_nhapmatkhau = NULL;lv_obj_t *ui_keyboard = NULL;lv_obj_t *ui_settingmask5 = NULL;
// event funtions

// build funtions

void ui_settingwifi3_screen_init(void)
{
ui_settingwifi3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_settingwifi3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingwifi3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingwifi3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_iconwifi1 = lv_img_create(ui_settingwifi3);
lv_img_set_src(ui_iconwifi1, &ui_img_iconwifi_small_png);
lv_obj_set_width( ui_iconwifi1, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_iconwifi1, LV_SIZE_CONTENT);   /// 15
lv_obj_set_x( ui_iconwifi1, 0 );
lv_obj_set_y( ui_iconwifi1, -90 );
lv_obj_set_align( ui_iconwifi1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_iconwifi1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_iconwifi1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ngoacnhonlen1 = lv_img_create(ui_settingwifi3);
lv_img_set_src(ui_ngoacnhonlen1, &ui_img_ngocnhonlen_png);
lv_obj_set_width( ui_ngoacnhonlen1, LV_SIZE_CONTENT);  /// 6
lv_obj_set_height( ui_ngoacnhonlen1, LV_SIZE_CONTENT);   /// 6
lv_obj_set_x( ui_ngoacnhonlen1, 0 );
lv_obj_set_y( ui_ngoacnhonlen1, 90 );
lv_obj_set_align( ui_ngoacnhonlen1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ngoacnhonlen1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ngoacnhonlen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_passwordbutton = lv_img_create(ui_settingwifi3);
lv_img_set_src(ui_passwordbutton, &ui_img_bar_wifisetting_png);
lv_obj_set_width( ui_passwordbutton, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_passwordbutton, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_passwordbutton, 0 );
lv_obj_set_y( ui_passwordbutton, -24 );
lv_obj_set_align( ui_passwordbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_passwordbutton, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_passwordbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_password = lv_label_create(ui_passwordbutton);
lv_obj_set_width( ui_password, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_password, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_password, 0 );
lv_obj_set_y( ui_password, 4 );
lv_obj_set_align( ui_password, LV_ALIGN_CENTER );
lv_label_set_text(ui_password,"****************");
lv_obj_set_style_text_color(ui_password, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_password, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_password, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_password, &ui_font_SVNAvo16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_enterbutton = lv_img_create(ui_passwordbutton);
lv_img_set_src(ui_enterbutton, &ui_img_ngoacnhonphai_png);
lv_obj_set_width( ui_enterbutton, LV_SIZE_CONTENT);  /// 5
lv_obj_set_height( ui_enterbutton, LV_SIZE_CONTENT);   /// 6
lv_obj_set_x( ui_enterbutton, 68 );
lv_obj_set_y( ui_enterbutton, 0 );
lv_obj_set_align( ui_enterbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_enterbutton, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_enterbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_nhapmatkhau = lv_label_create(ui_settingwifi3);
lv_obj_set_width( ui_nhapmatkhau, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_nhapmatkhau, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_nhapmatkhau, 0 );
lv_obj_set_y( ui_nhapmatkhau, -54 );
lv_obj_set_align( ui_nhapmatkhau, LV_ALIGN_CENTER );
lv_label_set_text(ui_nhapmatkhau,"Nhap mat khau");
lv_obj_set_style_text_color(ui_nhapmatkhau, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_nhapmatkhau, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_nhapmatkhau, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_nhapmatkhau, &ui_font_SVNAvo16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_keyboard = lv_img_create(ui_settingwifi3);
lv_img_set_src(ui_keyboard, &ui_img_keyboard_png);
lv_obj_set_width( ui_keyboard, LV_SIZE_CONTENT);  /// 163
lv_obj_set_height( ui_keyboard, LV_SIZE_CONTENT);   /// 88
lv_obj_set_x( ui_keyboard, 0 );
lv_obj_set_y( ui_keyboard, 40 );
lv_obj_set_align( ui_keyboard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_keyboard, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_keyboard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingmask5 = lv_img_create(ui_settingwifi3);
lv_img_set_src(ui_settingmask5, &ui_img_setting_mask_png);
lv_obj_set_width( ui_settingmask5, LV_SIZE_CONTENT);  /// 241
lv_obj_set_height( ui_settingmask5, LV_SIZE_CONTENT);   /// 241
lv_obj_set_align( ui_settingmask5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_settingmask5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_settingmask5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_settingwifi3 = ui_settingwifi3;
uic_ngoacnhonlen1 = ui_ngoacnhonlen1;
uic_passwordbutton = ui_passwordbutton;
uic_password = ui_password;
uic_enterbutton = ui_enterbutton;
uic_keyboard = ui_keyboard;

}

void ui_settingwifi3_screen_destroy(void)
{
   if (ui_settingwifi3) lv_obj_del(ui_settingwifi3);

// NULL screen variables
uic_settingwifi3= NULL;
ui_settingwifi3= NULL;
ui_iconwifi1= NULL;
uic_ngoacnhonlen1= NULL;
ui_ngoacnhonlen1= NULL;
uic_passwordbutton= NULL;
ui_passwordbutton= NULL;
uic_password= NULL;
ui_password= NULL;
uic_enterbutton= NULL;
ui_enterbutton= NULL;
ui_nhapmatkhau= NULL;
uic_keyboard= NULL;
ui_keyboard= NULL;
ui_settingmask5= NULL;

}

void ui_settingwifi3_screen_relocalize(void)
{
// label widgets on screen

}
