// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"

lv_obj_t *uic_timeonscreen;
lv_obj_t *uic_screentimebutton;
lv_obj_t *uic_settingscreentime;
lv_obj_t *ui_settingscreentime = NULL;lv_obj_t *ui_screentimebutton = NULL;lv_obj_t *ui_ngocnhontrai = NULL;lv_obj_t *ui_ngoacnhonphai = NULL;lv_obj_t *ui_timeonscreen = NULL;lv_obj_t *ui_screentime = NULL;lv_obj_t *ui_settingmask2 = NULL;
// event funtions

// build funtions

void ui_settingscreentime_screen_init(void)
{
ui_settingscreentime = lv_obj_create(NULL);
lv_obj_clear_flag( ui_settingscreentime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingscreentime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingscreentime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_screentimebutton = lv_img_create(ui_settingscreentime);
lv_img_set_src(ui_screentimebutton, &ui_img_bar_screentime_png);
lv_obj_set_width( ui_screentimebutton, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_screentimebutton, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_screentimebutton, 0 );
lv_obj_set_y( ui_screentimebutton, 22 );
lv_obj_set_align( ui_screentimebutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_screentimebutton, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_screentimebutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ngocnhontrai = lv_img_create(ui_screentimebutton);
lv_img_set_src(ui_ngocnhontrai, &ui_img_ngoacnhontrai_png);
lv_obj_set_width( ui_ngocnhontrai, LV_SIZE_CONTENT);  /// 5
lv_obj_set_height( ui_ngocnhontrai, LV_SIZE_CONTENT);   /// 6
lv_obj_set_x( ui_ngocnhontrai, -20 );
lv_obj_set_y( ui_ngocnhontrai, 0 );
lv_obj_set_align( ui_ngocnhontrai, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ngocnhontrai, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ngocnhontrai, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ngoacnhonphai = lv_img_create(ui_screentimebutton);
lv_img_set_src(ui_ngoacnhonphai, &ui_img_ngoacnhonphai_png);
lv_obj_set_width( ui_ngoacnhonphai, LV_SIZE_CONTENT);  /// 5
lv_obj_set_height( ui_ngoacnhonphai, LV_SIZE_CONTENT);   /// 6
lv_obj_set_x( ui_ngoacnhonphai, 20 );
lv_obj_set_y( ui_ngoacnhonphai, 0 );
lv_obj_set_align( ui_ngoacnhonphai, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ngoacnhonphai, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ngoacnhonphai, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timeonscreen = lv_label_create(ui_screentimebutton);
lv_obj_set_width( ui_timeonscreen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeonscreen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeonscreen, 0 );
lv_obj_set_y( ui_timeonscreen, -2 );
lv_obj_set_align( ui_timeonscreen, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeonscreen,"30");
lv_obj_set_style_text_color(ui_timeonscreen, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeonscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timeonscreen, &ui_font_SVNRounded23, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_screentime = lv_img_create(ui_settingscreentime);
lv_img_set_src(ui_screentime, &ui_img_screentime_png);
lv_obj_set_width( ui_screentime, LV_SIZE_CONTENT);  /// 36
lv_obj_set_height( ui_screentime, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_screentime, 0 );
lv_obj_set_y( ui_screentime, -24 );
lv_obj_set_align( ui_screentime, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_screentime, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_screentime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingmask2 = lv_img_create(ui_settingscreentime);
lv_img_set_src(ui_settingmask2, &ui_img_setting_mask_png);
lv_obj_set_width( ui_settingmask2, LV_SIZE_CONTENT);  /// 241
lv_obj_set_height( ui_settingmask2, LV_SIZE_CONTENT);   /// 241
lv_obj_set_align( ui_settingmask2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_settingmask2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_settingmask2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_settingscreentime = ui_settingscreentime;
uic_screentimebutton = ui_screentimebutton;
uic_timeonscreen = ui_timeonscreen;

}

void ui_settingscreentime_screen_destroy(void)
{
   if (ui_settingscreentime) lv_obj_del(ui_settingscreentime);

// NULL screen variables
uic_settingscreentime= NULL;
ui_settingscreentime= NULL;
uic_screentimebutton= NULL;
ui_screentimebutton= NULL;
ui_ngocnhontrai= NULL;
ui_ngoacnhonphai= NULL;
uic_timeonscreen= NULL;
ui_timeonscreen= NULL;
ui_screentime= NULL;
ui_settingmask2= NULL;

}

void ui_settingscreentime_screen_relocalize(void)
{
// label widgets on screen

}
