// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_SETTINGSCREENTIME_H
#define UI_SETTINGSCREENTIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingscreentime
extern void ui_settingscreentime_screen_init(void);
extern void ui_settingscreentime_screen_destroy(void);
extern void ui_settingscreentime_screen_relocalize(void);
extern lv_obj_t *ui_settingscreentime;
extern lv_obj_t *ui_screentimebutton;
extern lv_obj_t *ui_ngocnhontrai;
extern lv_obj_t *ui_ngoacnhonphai;
extern lv_obj_t *ui_timeonscreen;
extern lv_obj_t *ui_screentime;
extern lv_obj_t *ui_settingmask2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingscreentime;
extern lv_obj_t *uic_screentimebutton;
extern lv_obj_t *uic_timeonscreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

