// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_SETTINGBLE1_H
#define UI_SETTINGBLE1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingble1
extern void ui_settingble1_screen_init(void);
extern void ui_settingble1_screen_destroy(void);
extern void ui_settingble1_screen_relocalize(void);
extern lv_obj_t *ui_settingble1;
extern lv_obj_t *ui_blebutton;
extern lv_obj_t *ui_blestatus;
extern lv_obj_t *ui_bledisconnect1;
extern lv_obj_t *ui_bleconnect1;
extern lv_obj_t *ui_settingmask6;
extern lv_obj_t *ui_bledeviceconnected;
extern lv_obj_t *ui_loadingble;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingble1;
extern lv_obj_t *uic_blebutton;
extern lv_obj_t *uic_blestatus;
extern lv_obj_t *uic_bledisconnect1;
extern lv_obj_t *uic_bledeviceconnected;
extern lv_obj_t *uic_loadingble;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

