// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_SETTINGWIFI2_H
#define UI_SETTINGWIFI2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingwifi2
extern void ui_settingwifi2_screen_init(void);
extern void ui_settingwifi2_screen_destroy(void);
extern void ui_settingwifi2_screen_relocalize(void);
extern lv_obj_t *ui_settingwifi2;
extern lv_obj_t *ui_ssid_1;
extern lv_obj_t *ui_ssid_2;
extern lv_obj_t *ui_ssid_3;
extern lv_obj_t *ui_ssid_4;
extern lv_obj_t *ui_ssid_5;
extern lv_obj_t *ui_selectssid;
extern lv_obj_t *ui_iconwifi;
extern lv_obj_t *ui_iconwificonnect;
extern lv_obj_t *ui_resetbluetooth;
extern lv_obj_t *ui_bleconnectstatussmall;
extern lv_obj_t *ui_bleconnectsucess;
extern lv_obj_t *ui_settingmask4;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingwifi2;
extern lv_obj_t *uic_ssid_1;
extern lv_obj_t *uic_ssid_2;
extern lv_obj_t *uic_ssid_3;
extern lv_obj_t *uic_ssid_4;
extern lv_obj_t *uic_ssid_5;
extern lv_obj_t *uic_selectssid;
extern lv_obj_t *uic_iconwifi;
extern lv_obj_t *uic_resetbluetooth;
extern lv_obj_t *uic_connectstatus;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

