// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"

lv_obj_t *uic_bledisconnecticon;
lv_obj_t *uic_bleconnectstatus;
lv_obj_t *uic_resetwifi;
lv_obj_t *uic_selectssidtoconnect;
lv_obj_t *uic_bledevice1;
lv_obj_t *uic_bledevice2;
lv_obj_t *uic_bledevice3;
lv_obj_t *uic_bledevice4;
lv_obj_t *uic_bledevice5;
lv_obj_t *uic_settingble2;
lv_obj_t *ui_settingble2 = NULL;lv_obj_t *ui_bledevice5 = NULL;lv_obj_t *ui_bledevice4 = NULL;lv_obj_t *ui_bledevice3 = NULL;lv_obj_t *ui_bledevice2 = NULL;lv_obj_t *ui_bledevice1 = NULL;lv_obj_t *ui_selectssidtoconnect = NULL;lv_obj_t *ui_resetwifi = NULL;lv_obj_t *ui_bleconnectstatus = NULL;lv_obj_t *ui_connectsuccess = NULL;lv_obj_t *ui_bledisconnecticon = NULL;lv_obj_t *ui_bleconecticon = NULL;lv_obj_t *ui_settingmask7 = NULL;
// event funtions

// build funtions

void ui_settingble2_screen_init(void)
{
ui_settingble2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_settingble2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingble2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingble2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bledevice5 = lv_label_create(ui_settingble2);
lv_obj_set_width( ui_bledevice5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bledevice5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bledevice5, -5 );
lv_obj_set_y( ui_bledevice5, -48 );
lv_obj_set_align( ui_bledevice5, LV_ALIGN_CENTER );
lv_label_set_text(ui_bledevice5,"Nanananana");
lv_obj_set_style_text_color(ui_bledevice5, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bledevice5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_bledevice5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bledevice5, &ui_font_SVNAvo16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bledevice4 = lv_label_create(ui_settingble2);
lv_obj_set_width( ui_bledevice4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bledevice4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bledevice4, -5 );
lv_obj_set_y( ui_bledevice4, -24 );
lv_obj_set_align( ui_bledevice4, LV_ALIGN_CENTER );
lv_label_set_text(ui_bledevice4,"Samsung Gala...");
lv_obj_set_style_text_color(ui_bledevice4, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bledevice4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_bledevice4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bledevice4, &ui_font_SVNAvo16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bledevice3 = lv_label_create(ui_settingble2);
lv_obj_set_width( ui_bledevice3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bledevice3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bledevice3, -5 );
lv_obj_set_y( ui_bledevice3, 48 );
lv_obj_set_align( ui_bledevice3, LV_ALIGN_CENTER );
lv_label_set_text(ui_bledevice3,"hehhehe");
lv_obj_set_style_text_color(ui_bledevice3, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bledevice3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_bledevice3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bledevice3, &ui_font_SVNAvo16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bledevice2 = lv_label_create(ui_settingble2);
lv_obj_set_width( ui_bledevice2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bledevice2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bledevice2, -5 );
lv_obj_set_y( ui_bledevice2, 24 );
lv_obj_set_align( ui_bledevice2, LV_ALIGN_CENTER );
lv_label_set_text(ui_bledevice2,"Nokia 2G");
lv_obj_set_style_text_color(ui_bledevice2, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bledevice2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_bledevice2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bledevice2, &ui_font_SVNAvo16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bledevice1 = lv_label_create(ui_settingble2);
lv_obj_set_width( ui_bledevice1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bledevice1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bledevice1, -5 );
lv_obj_set_y( ui_bledevice1, 0 );
lv_obj_set_align( ui_bledevice1, LV_ALIGN_CENTER );
lv_label_set_text(ui_bledevice1,"iPhone cua Kha");
lv_obj_set_style_text_color(ui_bledevice1, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bledevice1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_bledevice1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bledevice1, &ui_font_SVNAvo16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectssidtoconnect = lv_label_create(ui_settingble2);
lv_obj_set_width( ui_selectssidtoconnect, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectssidtoconnect, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectssidtoconnect, -5 );
lv_obj_set_y( ui_selectssidtoconnect, 0 );
lv_obj_set_align( ui_selectssidtoconnect, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectssidtoconnect,"iPhone cua Kha");
lv_obj_set_style_text_color(ui_selectssidtoconnect, lv_color_hex(0xFF9B45), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectssidtoconnect, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_selectssidtoconnect, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectssidtoconnect, &ui_font_SVNAvo16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_resetwifi = lv_img_create(ui_settingble2);
lv_img_set_src(ui_resetwifi, &ui_img_ngocnhonlen_png);
lv_obj_set_width( ui_resetwifi, LV_SIZE_CONTENT);  /// 6
lv_obj_set_height( ui_resetwifi, LV_SIZE_CONTENT);   /// 6
lv_obj_set_x( ui_resetwifi, 0 );
lv_obj_set_y( ui_resetwifi, 90 );
lv_obj_set_align( ui_resetwifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_resetwifi, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_resetwifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_bleconnectstatus = lv_img_create(ui_settingble2);
lv_img_set_src(ui_bleconnectstatus, &ui_img_loading_png);
lv_obj_set_width( ui_bleconnectstatus, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_bleconnectstatus, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_bleconnectstatus, -75 );
lv_obj_set_y( ui_bleconnectstatus, 0 );
lv_obj_set_align( ui_bleconnectstatus, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bleconnectstatus, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_bleconnectstatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_connectsuccess = lv_img_create(ui_bleconnectstatus);
lv_img_set_src(ui_connectsuccess, &ui_img_connect_success_small_png);
lv_obj_set_width( ui_connectsuccess, LV_SIZE_CONTENT);  /// 15
lv_obj_set_height( ui_connectsuccess, LV_SIZE_CONTENT);   /// 15
lv_obj_set_x( ui_connectsuccess, -1 );
lv_obj_set_y( ui_connectsuccess, -1 );
lv_obj_set_align( ui_connectsuccess, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_connectsuccess, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_connectsuccess, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_bledisconnecticon = lv_img_create(ui_settingble2);
lv_img_set_src(ui_bledisconnecticon, &ui_img_ble_disconnect_icon_png);
lv_obj_set_width( ui_bledisconnecticon, LV_SIZE_CONTENT);  /// 10
lv_obj_set_height( ui_bledisconnecticon, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_bledisconnecticon, 0 );
lv_obj_set_y( ui_bledisconnecticon, -90 );
lv_obj_set_align( ui_bledisconnecticon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bledisconnecticon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_bledisconnecticon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_bleconecticon = lv_img_create(ui_bledisconnecticon);
lv_img_set_src(ui_bleconecticon, &ui_img_ble_connect_icon_png);
lv_obj_set_width( ui_bleconecticon, LV_SIZE_CONTENT);  /// 9
lv_obj_set_height( ui_bleconecticon, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_bleconecticon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bleconecticon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_bleconecticon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingmask7 = lv_img_create(ui_settingble2);
lv_img_set_src(ui_settingmask7, &ui_img_setting_mask_png);
lv_obj_set_width( ui_settingmask7, LV_SIZE_CONTENT);  /// 241
lv_obj_set_height( ui_settingmask7, LV_SIZE_CONTENT);   /// 241
lv_obj_set_align( ui_settingmask7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_settingmask7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_settingmask7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_settingble2 = ui_settingble2;
uic_bledevice5 = ui_bledevice5;
uic_bledevice4 = ui_bledevice4;
uic_bledevice3 = ui_bledevice3;
uic_bledevice2 = ui_bledevice2;
uic_bledevice1 = ui_bledevice1;
uic_selectssidtoconnect = ui_selectssidtoconnect;
uic_resetwifi = ui_resetwifi;
uic_bleconnectstatus = ui_bleconnectstatus;
uic_bledisconnecticon = ui_bledisconnecticon;

}

void ui_settingble2_screen_destroy(void)
{
   if (ui_settingble2) lv_obj_del(ui_settingble2);

// NULL screen variables
uic_settingble2= NULL;
ui_settingble2= NULL;
uic_bledevice5= NULL;
ui_bledevice5= NULL;
uic_bledevice4= NULL;
ui_bledevice4= NULL;
uic_bledevice3= NULL;
ui_bledevice3= NULL;
uic_bledevice2= NULL;
ui_bledevice2= NULL;
uic_bledevice1= NULL;
ui_bledevice1= NULL;
uic_selectssidtoconnect= NULL;
ui_selectssidtoconnect= NULL;
uic_resetwifi= NULL;
ui_resetwifi= NULL;
uic_bleconnectstatus= NULL;
ui_bleconnectstatus= NULL;
ui_connectsuccess= NULL;
uic_bledisconnecticon= NULL;
ui_bledisconnecticon= NULL;
ui_bleconecticon= NULL;
ui_settingmask7= NULL;

}

void ui_settingble2_screen_relocalize(void)
{
// label widgets on screen

}
