// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_SETTINGWIFI3_H
#define UI_SETTINGWIFI3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingwifi3
extern void ui_settingwifi3_screen_init(void);
extern void ui_settingwifi3_screen_destroy(void);
extern void ui_settingwifi3_screen_relocalize(void);
extern lv_obj_t *ui_settingwifi3;
extern lv_obj_t *ui_iconwifi1;
extern lv_obj_t *ui_ngoacnhonlen1;
extern lv_obj_t *ui_passwordbutton;
extern lv_obj_t *ui_password;
extern lv_obj_t *ui_enterbutton;
extern lv_obj_t *ui_nhapmatkhau;
extern lv_obj_t *ui_keyboard;
extern lv_obj_t *ui_settingmask5;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingwifi3;
extern lv_obj_t *uic_ngoacnhonlen1;
extern lv_obj_t *uic_passwordbutton;
extern lv_obj_t *uic_password;
extern lv_obj_t *uic_enterbutton;
extern lv_obj_t *uic_keyboard;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

