// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_SETTINGWIFI_H
#define UI_SETTINGWIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingwifi
extern void ui_settingwifi_screen_init(void);
extern void ui_settingwifi_screen_destroy(void);
extern void ui_settingwifi_screen_relocalize(void);
extern lv_obj_t *ui_settingwifi;
extern lv_obj_t *ui_wifibutton;
extern lv_obj_t *ui_wifistatus;
extern lv_obj_t *ui_wifistatusicon;
extern lv_obj_t *ui_wificonnect1;
extern lv_obj_t *ui_ssidconnected;
extern lv_obj_t *ui_loading;
extern lv_obj_t *ui_settingmask3;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingwifi;
extern lv_obj_t *uic_wifibutton;
extern lv_obj_t *uic_wifistatus;
extern lv_obj_t *uic_wifistatusicon;
extern lv_obj_t *uic_ssidconnected;
extern lv_obj_t *uic_loading;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

