// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_SETTINGBRIGHTNESS_H
#define UI_SETTINGBRIGHTNESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingbrightness
extern void ui_settingbrightness_screen_init(void);
extern void ui_settingbrightness_screen_destroy(void);
extern void ui_settingbrightness_screen_relocalize(void);
extern lv_obj_t *ui_settingbrightness;
extern lv_obj_t *ui_brightness;
extern lv_obj_t *ui_brightnessbutton;
extern lv_obj_t *ui_adjustbrightness;
extern lv_obj_t *ui_settingmask1;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingbrightness;
extern lv_obj_t *uic_brightnessbutton;
extern lv_obj_t *uic_adjustbrightness;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

