// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"

lv_obj_t *uic_loadingble;
lv_obj_t *uic_bledeviceconnected;
lv_obj_t *uic_bledisconnect1;
lv_obj_t *uic_blestatus;
lv_obj_t *uic_blebutton;
lv_obj_t *uic_settingble1;
lv_obj_t *ui_settingble1 = NULL;lv_obj_t *ui_blebutton = NULL;lv_obj_t *ui_blestatus = NULL;lv_obj_t *ui_bledisconnect1 = NULL;lv_obj_t *ui_bleconnect1 = NULL;lv_obj_t *ui_settingmask6 = NULL;lv_obj_t *ui_bledeviceconnected = NULL;lv_obj_t *ui_loadingble = NULL;
// event funtions

// build funtions

void ui_settingble1_screen_init(void)
{
ui_settingble1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_settingble1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingble1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingble1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_blebutton = lv_img_create(ui_settingble1);
lv_img_set_src(ui_blebutton, &ui_img_bar_ble_png);
lv_obj_set_width( ui_blebutton, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_blebutton, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_blebutton, 0 );
lv_obj_set_y( ui_blebutton, 22 );
lv_obj_set_align( ui_blebutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_blebutton, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_blebutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_blestatus = lv_label_create(ui_blebutton);
lv_obj_set_width( ui_blestatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_blestatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_blestatus, 0 );
lv_obj_set_y( ui_blestatus, -2 );
lv_obj_set_align( ui_blestatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_blestatus,"TIM KIEM");
lv_obj_set_style_text_color(ui_blestatus, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_blestatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_blestatus, &ui_font_SVNRounded23, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bledisconnect1 = lv_img_create(ui_settingble1);
lv_img_set_src(ui_bledisconnect1, &ui_img_ble_disconnect_1_png);
lv_obj_set_width( ui_bledisconnect1, LV_SIZE_CONTENT);  /// 53
lv_obj_set_height( ui_bledisconnect1, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_bledisconnect1, 0 );
lv_obj_set_y( ui_bledisconnect1, -24 );
lv_obj_set_align( ui_bledisconnect1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bledisconnect1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_bledisconnect1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_bleconnect1 = lv_img_create(ui_bledisconnect1);
lv_img_set_src(ui_bleconnect1, &ui_img_ble_connect_1_png);
lv_obj_set_width( ui_bleconnect1, LV_SIZE_CONTENT);  /// 53
lv_obj_set_height( ui_bleconnect1, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_bleconnect1, 1 );
lv_obj_set_y( ui_bleconnect1, 0 );
lv_obj_set_align( ui_bleconnect1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bleconnect1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_bleconnect1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingmask6 = lv_img_create(ui_settingble1);
lv_img_set_src(ui_settingmask6, &ui_img_setting_mask_png);
lv_obj_set_width( ui_settingmask6, LV_SIZE_CONTENT);  /// 241
lv_obj_set_height( ui_settingmask6, LV_SIZE_CONTENT);   /// 241
lv_obj_set_align( ui_settingmask6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_settingmask6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_settingmask6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_bledeviceconnected = lv_label_create(ui_settingble1);
lv_obj_set_width( ui_bledeviceconnected, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bledeviceconnected, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bledeviceconnected, 0 );
lv_obj_set_y( ui_bledeviceconnected, 55 );
lv_obj_set_align( ui_bledeviceconnected, LV_ALIGN_CENTER );
lv_label_set_text(ui_bledeviceconnected,"iPhone cua Kha");
lv_obj_set_style_text_color(ui_bledeviceconnected, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bledeviceconnected, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_bledeviceconnected, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bledeviceconnected, &ui_font_SVNAvo16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_loadingble = lv_img_create(ui_bledeviceconnected);
lv_img_set_src(ui_loadingble, &ui_img_loading_png);
lv_obj_set_width( ui_loadingble, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_loadingble, LV_SIZE_CONTENT);   /// 16
lv_obj_set_align( ui_loadingble, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_loadingble, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_loadingble, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_settingble1 = ui_settingble1;
uic_blebutton = ui_blebutton;
uic_blestatus = ui_blestatus;
uic_bledisconnect1 = ui_bledisconnect1;
uic_bledeviceconnected = ui_bledeviceconnected;
uic_loadingble = ui_loadingble;

}

void ui_settingble1_screen_destroy(void)
{
   if (ui_settingble1) lv_obj_del(ui_settingble1);

// NULL screen variables
uic_settingble1= NULL;
ui_settingble1= NULL;
uic_blebutton= NULL;
ui_blebutton= NULL;
uic_blestatus= NULL;
ui_blestatus= NULL;
uic_bledisconnect1= NULL;
ui_bledisconnect1= NULL;
ui_bleconnect1= NULL;
ui_settingmask6= NULL;
uic_bledeviceconnected= NULL;
ui_bledeviceconnected= NULL;
uic_loadingble= NULL;
ui_loadingble= NULL;

}

void ui_settingble1_screen_relocalize(void)
{
// label widgets on screen

}
