// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"

lv_obj_t *uic_adjustbrightness;
lv_obj_t *uic_brightnessbutton;
lv_obj_t *uic_settingbrightness;
lv_obj_t *ui_settingbrightness = NULL;lv_obj_t *ui_brightness = NULL;lv_obj_t *ui_brightnessbutton = NULL;lv_obj_t *ui_adjustbrightness = NULL;lv_obj_t *ui_settingmask1 = NULL;
// event funtions

// build funtions

void ui_settingbrightness_screen_init(void)
{
ui_settingbrightness = lv_obj_create(NULL);
lv_obj_clear_flag( ui_settingbrightness, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingbrightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingbrightness, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightness = lv_img_create(ui_settingbrightness);
lv_img_set_src(ui_brightness, &ui_img_brightness_png);
lv_obj_set_width( ui_brightness, LV_SIZE_CONTENT);  /// 39
lv_obj_set_height( ui_brightness, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_brightness, 0 );
lv_obj_set_y( ui_brightness, -24 );
lv_obj_set_align( ui_brightness, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_brightness, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_brightness, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_brightnessbutton = lv_img_create(ui_settingbrightness);
lv_img_set_src(ui_brightnessbutton, &ui_img_bar_brightness_png);
lv_obj_set_width( ui_brightnessbutton, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_brightnessbutton, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_brightnessbutton, 0 );
lv_obj_set_y( ui_brightnessbutton, 22 );
lv_obj_set_align( ui_brightnessbutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_brightnessbutton, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_brightnessbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_adjustbrightness = lv_img_create(ui_brightnessbutton);
lv_img_set_src(ui_adjustbrightness, &ui_img_adjust_brightness_png);
lv_obj_set_width( ui_adjustbrightness, LV_SIZE_CONTENT);  /// 128
lv_obj_set_height( ui_adjustbrightness, LV_SIZE_CONTENT);   /// 4
lv_obj_set_align( ui_adjustbrightness, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_adjustbrightness, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_adjustbrightness, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingmask1 = lv_img_create(ui_settingbrightness);
lv_img_set_src(ui_settingmask1, &ui_img_setting_mask_png);
lv_obj_set_width( ui_settingmask1, LV_SIZE_CONTENT);  /// 241
lv_obj_set_height( ui_settingmask1, LV_SIZE_CONTENT);   /// 241
lv_obj_set_align( ui_settingmask1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_settingmask1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_settingmask1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_settingbrightness = ui_settingbrightness;
uic_brightnessbutton = ui_brightnessbutton;
uic_adjustbrightness = ui_adjustbrightness;

}

void ui_settingbrightness_screen_destroy(void)
{
   if (ui_settingbrightness) lv_obj_del(ui_settingbrightness);

// NULL screen variables
uic_settingbrightness= NULL;
ui_settingbrightness= NULL;
ui_brightness= NULL;
uic_brightnessbutton= NULL;
ui_brightnessbutton= NULL;
uic_adjustbrightness= NULL;
ui_adjustbrightness= NULL;
ui_settingmask1= NULL;

}

void ui_settingbrightness_screen_relocalize(void)
{
// label widgets on screen

}
