// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"

lv_obj_t *uic_loading;
lv_obj_t *uic_ssidconnected;
lv_obj_t *uic_wifistatusicon;
lv_obj_t *uic_wifistatus;
lv_obj_t *uic_wifibutton;
lv_obj_t *uic_settingwifi;
lv_obj_t *ui_settingwifi = NULL;lv_obj_t *ui_wifibutton = NULL;lv_obj_t *ui_wifistatus = NULL;lv_obj_t *ui_wifistatusicon = NULL;lv_obj_t *ui_wificonnect1 = NULL;lv_obj_t *ui_ssidconnected = NULL;lv_obj_t *ui_loading = NULL;lv_obj_t *ui_settingmask3 = NULL;
// event funtions

// build funtions

void ui_settingwifi_screen_init(void)
{
ui_settingwifi = lv_obj_create(NULL);
lv_obj_clear_flag( ui_settingwifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_settingwifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingwifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifibutton = lv_img_create(ui_settingwifi);
lv_img_set_src(ui_wifibutton, &ui_img_bar_wifisetting_png);
lv_obj_set_width( ui_wifibutton, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_wifibutton, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_wifibutton, 0 );
lv_obj_set_y( ui_wifibutton, 22 );
lv_obj_set_align( ui_wifibutton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifibutton, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifibutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifistatus = lv_label_create(ui_wifibutton);
lv_obj_set_width( ui_wifistatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifistatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifistatus, 0 );
lv_obj_set_y( ui_wifistatus, -2 );
lv_obj_set_align( ui_wifistatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifistatus,"ket noi");
lv_obj_set_style_text_color(ui_wifistatus, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wifistatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifistatus, &ui_font_SVNRounded23, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifistatusicon = lv_img_create(ui_settingwifi);
lv_img_set_src(ui_wifistatusicon, &ui_img_wifi_disconnect_2_png);
lv_obj_set_width( ui_wifistatusicon, LV_SIZE_CONTENT);  /// 51
lv_obj_set_height( ui_wifistatusicon, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_wifistatusicon, 0 );
lv_obj_set_y( ui_wifistatusicon, -24 );
lv_obj_set_align( ui_wifistatusicon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifistatusicon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifistatusicon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wificonnect1 = lv_img_create(ui_wifistatusicon);
lv_img_set_src(ui_wificonnect1, &ui_img_wifi_connect_1_png);
lv_obj_set_width( ui_wificonnect1, LV_SIZE_CONTENT);  /// 51
lv_obj_set_height( ui_wificonnect1, LV_SIZE_CONTENT);   /// 39
lv_obj_set_align( ui_wificonnect1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wificonnect1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wificonnect1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ssidconnected = lv_label_create(ui_settingwifi);
lv_obj_set_width( ui_ssidconnected, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ssidconnected, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ssidconnected, 0 );
lv_obj_set_y( ui_ssidconnected, 55 );
lv_obj_set_align( ui_ssidconnected, LV_ALIGN_CENTER );
lv_label_set_text(ui_ssidconnected,"Bun thit nuong");
lv_obj_set_style_text_color(ui_ssidconnected, lv_color_hex(0xF4E7E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ssidconnected, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ssidconnected, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ssidconnected, &ui_font_SVNAvo16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_loading = lv_img_create(ui_ssidconnected);
lv_img_set_src(ui_loading, &ui_img_loading_png);
lv_obj_set_width( ui_loading, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_loading, LV_SIZE_CONTENT);   /// 16
lv_obj_set_align( ui_loading, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_loading, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_loading, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingmask3 = lv_img_create(ui_settingwifi);
lv_img_set_src(ui_settingmask3, &ui_img_setting_mask_png);
lv_obj_set_width( ui_settingmask3, LV_SIZE_CONTENT);  /// 241
lv_obj_set_height( ui_settingmask3, LV_SIZE_CONTENT);   /// 241
lv_obj_set_align( ui_settingmask3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_settingmask3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_settingmask3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_settingwifi = ui_settingwifi;
uic_wifibutton = ui_wifibutton;
uic_wifistatus = ui_wifistatus;
uic_wifistatusicon = ui_wifistatusicon;
uic_ssidconnected = ui_ssidconnected;
uic_loading = ui_loading;

}

void ui_settingwifi_screen_destroy(void)
{
   if (ui_settingwifi) lv_obj_del(ui_settingwifi);

// NULL screen variables
uic_settingwifi= NULL;
ui_settingwifi= NULL;
uic_wifibutton= NULL;
ui_wifibutton= NULL;
uic_wifistatus= NULL;
ui_wifistatus= NULL;
uic_wifistatusicon= NULL;
ui_wifistatusicon= NULL;
ui_wificonnect1= NULL;
uic_ssidconnected= NULL;
ui_ssidconnected= NULL;
uic_loading= NULL;
ui_loading= NULL;
ui_settingmask3= NULL;

}

void ui_settingwifi_screen_relocalize(void)
{
// label widgets on screen

}
