// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_SETTINGBLE2_H
#define UI_SETTINGBLE2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingble2
extern void ui_settingble2_screen_init(void);
extern void ui_settingble2_screen_destroy(void);
extern void ui_settingble2_screen_relocalize(void);
extern lv_obj_t *ui_settingble2;
extern lv_obj_t *ui_bledevice5;
extern lv_obj_t *ui_bledevice4;
extern lv_obj_t *ui_bledevice3;
extern lv_obj_t *ui_bledevice2;
extern lv_obj_t *ui_bledevice1;
extern lv_obj_t *ui_selectssidtoconnect;
extern lv_obj_t *ui_resetwifi;
extern lv_obj_t *ui_bleconnectstatus;
extern lv_obj_t *ui_connectsuccess;
extern lv_obj_t *ui_bledisconnecticon;
extern lv_obj_t *ui_bleconecticon;
extern lv_obj_t *ui_settingmask7;
// CUSTOM VARIABLES
extern lv_obj_t *uic_settingble2;
extern lv_obj_t *uic_bledevice5;
extern lv_obj_t *uic_bledevice4;
extern lv_obj_t *uic_bledevice3;
extern lv_obj_t *uic_bledevice2;
extern lv_obj_t *uic_bledevice1;
extern lv_obj_t *uic_selectssidtoconnect;
extern lv_obj_t *uic_resetwifi;
extern lv_obj_t *uic_bleconnectstatus;
extern lv_obj_t *uic_bledisconnecticon;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

